server:
  port: ${SERVER_PORT}
spring:
  application:
    name: main-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  liquibase:
    change-log: db/changelog/master.yml

application:
  report-service:
    url: ${REPORT_SERVICE_SERVER_URL}