server:
  port: ${SERVER_PORT}
spring:
  application:
    name: main-service
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  liquibase:
    change-log: db/changelog/master.yml
application:
  gateway:
    url: ${GATEWAY_SERVER_URL}
  report-service:
    url: ${REPORT_SERVICE_SERVER_URL}
  file-service:
    url: ${FILE_SERVICE_SERVER_URL}
kafka:
  topic-name: mainServiceToFileService
  topic-partitions: 5
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
