server:
  port: ${SERVER_PORT}
spring:
  application:
    name: report-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}