version: "3.8"
name: rviplabs
services:

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: main-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  main-service:
    image: rviplabs-main-service
    build:
      context: ../
      dockerfile: main-service/Dockerfile
    environment:
      JDBC_PASSWORD: ${MAIN_SERVICE_JDBC_PASSWORD}
      JDBC_URL: ${MAIN_SERVICE_JDBC_URL}
      JDBC_USERNAME: ${MAIN_SERVICE_JDBC_USERNAME}
      SERVER_PORT: ${MAIN_SERVICE_SERVER_PORT}
    depends_on:
      - postgres

  report-service:
    image: rviplabs-report-service
    build:
      context: ../
      dockerfile: report-service/Dockerfile
    environment:
      JDBC_PASSWORD: ${REPORT_SERVICE_JDBC_PASSWORD}
      JDBC_URL: ${REPORT_SERVICE_JDBC_URL}
      JDBC_USERNAME: ${REPORT_SERVICE_JDBC_USERNAME}
      SERVER_PORT: ${REPORT_SERVICE_SERVER_PORT}
    depends_on:
      - postgres

  gateway:
    image: rviplabs-gateway
    ports:
      - "${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}"
    build:
      context: ../
      dockerfile: gateway/Dockerfile
    environment:
      MAIN_SERVICE_SERVER_URL: ${MAIN_SERVICE_SERVER_URL}
      REPORT_SERVICE_SERVER_URL: ${REPORT_SERVICE_SERVER_URL}
      SERVER_PORT: ${GATEWAY_SERVER_PORT}
    depends_on:
      - main-service
      - report-service
